version: '3.9'

services:
  postgres:
    image: postgres:17.5-alpine
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=cve_explorer_dev
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
